### ISSUE TITLE
TableBlock does not render

### ISSUE THREAD

**Issue by Adrian-Turjak** [noripyt/wagtail-react-streamfield#3] opened 2018-08-22 03:41 UTC
We use:
https://docs.wagtail.io/en/v2.2.1/reference/contrib/table_block.html

Testing with this Streamfield and the block doesn't render the table editor.

**Comment by BertrandBordage** [comment] 2018-08-22 07:39
Indeed. I thought it worked because adding a new block works, but turns out it doesn’t fully work with an existing value.

**Comment by BertrandBordage** [comment] 2018-08-22 15:21
OK, Handsontable is really annoying, I’m considering removing it from Wagtail… It just doesn’t render anything if the HTML is not visible, and even with workarounds, the results are partially broken.
I thought updating Handsontable from 0.24.2 to 5.0.1 (!) would fix it, but absolutely not. Nothing changes.

I’ll apply the awful fix recommended by the official pro team of Handsontable: re-instantiate the table every time someone opens a block. Terrible.

**Comment by Adrian-Turjak** [comment] 2018-08-23 04:58
Is there an alternative to Handsontable? I looked by all the other options look worse.

**Comment by BertrandBordage** [comment] 2018-08-26 17:11
Same here, I couldn’t find a good alternative to Handsontable…
However, by cleaning and reworking some of the JavaScript from react-streamfield, I made it fully work, including duplication!

So fixed by noripyt/react-streamfield@ba9123170a9038864eaa46d2b0a4de7a454b0b44. Will be in wagtail-react-streamfield shortly.

**Closed by BertrandBordage** 2018-08-26 17:11 UTC
Labels: bug

**Comment by BertrandBordage** [comment] 2018-08-26 19:54
Fix released in 0.8.3.

**Comment by pimarc** [comment] 2020-02-17 15:47
Similar issue with last versions of wagtail and wagtail-react-streamfield
A new table is correctly displayed in the editor but not a previously saved one.
In chrome if you attempt to inspect the element with inspector it's miraculously displayed (no with firefox). It seams that some javascritpt init is missing somewhere.

**Comment by pimarc** [comment] 2020-02-17 16:27
I investigated more...
In fact the issue comes from the closed attribute of wagtail-react-streamfield that I always set to True in order to have something readable. If the table block streamfield or one of its parent streamfield has the closed attibute set, the table data is not displayed when rendering the page in admin so the height calculation of the table data is not correct when you open the table field.
In order to reproduce, juste create a table block streamfield with the closed attribute set.
I think some kind of event is necesssary to calculate the height of the table data when react-streamfield opens the item.
